version: '2'

volumes:
  orderer.insurance.com:
  peer0.insurer1.insurance.com:
  peer0.insurer2.insurance.com:
  peer0.reinsurer.insurance.com:
  peer0.externalsystem.insurance.com:

networks:
  insurance:

services:

  ca.insurer1.insurance.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.insurer1.insurance.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurer1.insurance.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/5724ee70be5b31d8d26d76eaeeb414b053483ac79d45d575983563fd619773ec_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurer1.insurance.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/5724ee70be5b31d8d26d76eaeeb414b053483ac79d45d575983563fd619773ec_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto/crypto-config/peerOrganizations/insurer1.insurance.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../ca-home/insurer1:/etc/hyperledger/fabric-ca-server
    container_name: ca.insurer1.insurance.com
    networks:
      - insurance

  peer0.insurer1.insurance.com:
    container_name: peer0.insurer1.insurance.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.insurer1.insurance.com
      - CORE_PEER_ADDRESS=peer0.insurer1.insurance.com:7051
      # GOSSIP
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurer1.insurance.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurer1.insurance.com:7051
      # MSP
      - CORE_PEER_LOCALMSPID=Insurer1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peerOrganizations/insurer1.insurance.com/peers/peer0.insurer1.insurance.com/msp
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peerOrganizations/insurer1.insurance.com/peers/peer0.insurer1.insurance.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peerOrganizations/insurer1.insurance.com/peers/peer0.insurer1.insurance.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peerOrganizations/insurer1.insurance.com/peers/peer0.insurer1.insurance.com/tls/ca.crt
      # Logging
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info         
      # Ledger - CouchDB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-insurer1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_insurance
      - CORE_PEER_PROFILE_ENABLED=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/crypto-config:/etc/hyperledger/crypto        
        - ./channel:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel
        - peer0.insurer1.insurance.com:/var/hyperledger/production

    networks:
      - insurance

  couchdb-insurer1:
    container_name: couchdb-insurer1
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - insurance

  ca.insurer2.insurance.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.insurer2.insurance.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurer2.insurance.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/804bed36f54a98c27ef4a47eeca5bca51470b72cbc576f4dad94ce3dcdb0c548_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurer2.insurance.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/804bed36f54a98c27ef4a47eeca5bca51470b72cbc576f4dad94ce3dcdb0c548_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto/crypto-config/peerOrganizations/insurer2.insurance.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../ca-home/insurer2:/etc/hyperledger/fabric-ca-server
    container_name: ca.insurer2.insurance.com
    networks:
      - insurance

  peer0.insurer2.insurance.com:
    container_name: peer0.insurer2.insurance.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.insurer2.insurance.com
      - CORE_PEER_ADDRESS=peer0.insurer2.insurance.com:7051
      # GOSSIP
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurer2.insurance.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurer2.insurance.com:7051
      # MSP
      - CORE_PEER_LOCALMSPID=Insurer2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      # Logging
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info         
      # Ledger - CouchDB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-insurer2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_insurance
      - CORE_PEER_PROFILE_ENABLED=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/crypto-config/peerOrganizations/insurer2.insurance.com/peers/peer0.insurer2.insurance.com:/etc/hyperledger/crypto/peer
        - peer0.insurer2.insurance.com:/var/hyperledger/production
    networks:
      - insurance

  couchdb-insurer2:
    container_name: couchdb-insurer2
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "6984:5984"
    networks:
      - insurance

  ca.reinsurer.insurance.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.reinsurer.insurance.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.reinsurer.insurance.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0d67439363daf61e6adec3d9630a7de293c58b9937681e17b04d773aaa369210_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.reinsurer.insurance.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0d67439363daf61e6adec3d9630a7de293c58b9937681e17b04d773aaa369210_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto/crypto-config/peerOrganizations/reinsurer.insurance.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../ca-home/reinsurer:/etc/hyperledger/fabric-ca-server
    container_name: ca.reinsurer.insurance.com
    networks:
      - insurance

  peer0.reinsurer.insurance.com:
    container_name: peer0.reinsurer.insurance.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.reinsurer.insurance.com
      - CORE_PEER_ADDRESS=peer0.reinsurer.insurance.com:7051
      # GOSSIP
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.reinsurer.insurance.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.reinsurer.insurance.com:7051
      # MSP
      - CORE_PEER_LOCALMSPID=ReInsurerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      # Logging
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info         
      # Ledger - CouchDB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-reinsurer:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_insurance
      - CORE_PEER_PROFILE_ENABLED=true      
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/crypto-config/peerOrganizations/reinsurer.insurance.com/peers/peer0.reinsurer.insurance.com:/etc/hyperledger/crypto/peer
        - peer0.reinsurer.insurance.com:/var/hyperledger/production
    networks:
      - insurance

  couchdb-reinsurer:
    container_name: couchdb-reinsurer
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "7984:5984"
    networks:
      - insurance

  ca.externalsystem.insurance.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.externalsystem.insurance.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.externalsystem.insurance.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/22986dffd82c64bb96e31bc257fbc4684ebb886ff92fcb5e3495feff66610486_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.externalsystem.insurance.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/22986dffd82c64bb96e31bc257fbc4684ebb886ff92fcb5e3495feff66610486_sk
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto/crypto-config/peerOrganizations/externalsystem.insurance.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../ca-home/externalsystem:/etc/hyperledger/fabric-ca-server
    container_name: ca.externalsystem.insurance.com
    networks:
      - insurance

  peer0.externalsystem.insurance.com:
    container_name: peer0.externalsystem.insurance.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.externalsystem.insurance.com
      - CORE_PEER_ADDRESS=peer0.externalsystem.insurance.com:7051
      # GOSSIP
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.externalsystem.insurance.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.externalsystem.insurance.com:7051
      # MSP
      - CORE_PEER_LOCALMSPID=ExternalSystemMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      # Logging
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info         
      # Ledger - CouchDB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-externalsystem:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_insurance
      - CORE_PEER_PROFILE_ENABLED=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 10051:7051
      - 10053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/crypto-config/peerOrganizations/externalsystem.insurance.com/peers/peer0.externalsystem.insurance.com:/etc/hyperledger/crypto/peer
        - peer0.externalsystem.insurance.com:/var/hyperledger/production
    networks:
      - insurance

  couchdb-externalsystem:
    container_name: couchdb-externalsystem
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "8984:5984"
    networks:
      - insurance

  orderer.insurance.com:
    container_name: orderer.insurance.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_GENERAL_LEDGERTYPE=json
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel/:/etc/hyperledger/configtx
        - ./crypto/crypto-config/ordererOrganizations/insurance.com/orderers/orderer.insurance.com:/etc/hyperledger/crypto/orderer
        - orderer.insurance.com:/var/hyperledger/production/orderer
    networks:
      - insurance

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.insurer1.insurance.com:7051
      - CORE_PEER_LOCALMSPID=Insurer1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurer1.insurance.com/users/Admin@insurer1.insurance.com/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurer1.insurance.com/peers/peer0.insurer1.insurance.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurer1.insurance.com/peers/peer0.insurer1.insurance.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurer1.insurance.com/peers/peer0.insurer1.insurance.com/tls/ca.crt
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
        - ./crypto/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel
    networks:
      - insurance
    #depends_on:
    # - orderer.insurance.com
    # - peer0.insurer1.insurance.com
    # - peer0.insurer2.insurance.com
    # - peer0.reinsurer.insurance.com
    # - peer0.externalsystem.insurance.com
